In [1]:
import pandas as pd
import requests

---

# Procurando e definindo os dados a serem buscados

In [163]:
# Identificadores segundo https://servicodados.ibge.gov.br/api/docs/agregados?versao=3#api-acervo
# - 125: Taxa de escolarização
# - 126: taxa de alfabetização
# - 127: Escolaridade
# - 27: Educação
# - 302: Educação de qualidade
# - 235: Frequência escolar
# - 179: Instrução e educação

def consulta_assunto(assunto):
  url = f'https://servicodados.ibge.gov.br/api/v3/agregados?assunto={assunto}'
  response = requests.get(url)
  response.raise_for_status()
  dados = response.json()
  return dados

def print_assuntos(dados):
  for linha in dados:
    nome = linha['nome']
    for agregado in linha['agregados']:
      print(f'{assunto} - {nome}: {agregado}')

In [164]:
assunto = 125
dados = consulta_assunto(assunto)
print_assuntos(dados)

125 - Indicadores de Desenvolvimento Sustentável: {'id': '1184', 'nome': 'Taxa de escolarização das pessoas de 5 a 24 anos de idade por grupos de idade (série encerrada)'}
125 - Indicadores de Desenvolvimento Sustentável: {'id': '1185', 'nome': 'Taxa de escolarização das pessoas de 7 a 14 anos de idade por sexo (série encerrada)'}
125 - Indicadores de Desenvolvimento Sustentável: {'id': '1186', 'nome': 'Taxa de escolarização das pessoas de 7 a 14 anos de idade por cor ou raça (série encerrada)'}

In [165]:
assunto = 126
dados = consulta_assunto(assunto)
print_assuntos(dados)

126 - Indicadores de Desenvolvimento Sustentável: {'id': '1187', 'nome': 'Taxa de alfabetização das pessoas de 15 anos ou mais de idade por sexo'}
126 - Indicadores de Desenvolvimento Sustentável: {'id': '1188', 'nome': 'Taxa de alfabetização das pessoas de 15 anos ou mais de idade, por cor ou raça'}

In [166]:
assunto = 127
dados = consulta_assunto(assunto)
print_assuntos(dados)

127 - Indicadores de Desenvolvimento Sustentável: {'id': '1189', 'nome': 'Média de anos de estudo das pessoas de 25 anos ou mais de idade por sexo (série encerrada)'}
127 - Indicadores de Desenvolvimento Sustentável: {'id': '1190', 'nome': 'Média de anos de estudo das pessoas de 25 anos ou mais de idade por cor ou raça (série encerrada)'}
127 - Indicadores de Desenvolvimento Sustentável: {'id': '3897', 'nome': 'Pessoas de 25 a 64 anos de idade e distribuição percentual, por grupos de anos de estudo'}
127 - Indicadores de Desenvolvimento Sustentável: {'id': '3898', 'nome': 'Pessoas de 25 a 64 anos de idade, total e com 11 anos de estudo, e respectiva proporção, por sexo'}
127 - Indicadores de Desenvolvimento Sustentável: {'id': '3899', 'nome': 'Pessoas de 25 a 64 anos de idade, total e com 11 anos de estudo, e respectiva proporção, por cor ou raça'}

In [167]:
assunto = 27
dados = consulta_assunto(assunto)
print_assuntos(dados)

27 - Censo Comum do Mercosul, Bolívia e Chile: {'id': '2082', 'nome': 'População de 5 anos ou mais de idade por grupos de anos de estudo, segundo o sexo e grupos de idade'}
27 - Censo Comum do Mercosul, Bolívia e Chile: {'id': '2083', 'nome': 'Pessoas de 5 anos ou mais de idade, que frequentavam escola por grupos de anos de estudo, segundo o sexo e grupos de idade'}
27 - Censo Comum do Mercosul, Bolívia e Chile: {'id': '2084', 'nome': 'Pessoas de 19 anos ou mais de idade por anos de estudo, segundo o sexo e idade'}
27 - Censo Comum do Mercosul, Bolívia e Chile: {'id': '2085', 'nome': 'Pessoas de 19 anos ou mais de idade por anos de estudo, segundo o sexo e grupos de idade'}
27 - Censo Demográfico: {'id': '10056', 'nome': 'Taxa bruta de frequência escolar, segundo os grupos de idade, o sexo e a cor ou raça'}
27 - Censo Demográfico: {'id': '10057', 'nome': 'Pessoas de até 5 anos de idade que frequentavam escola ou creche, por nível de ensino, segundo os grupos de idade, o sexo e a cor ou raça'}
27 - Censo Demográfico: {'id': '10058', 'nome': 'Pessoas de 6 a 17 anos de idade que frequentavam escola, por nível de ensino, segundo os grupos de idade, o sexo e a cor ou raça'}
27 - Censo Demográfico: {'id': '10059', 'nome': 'Pessoas de 18 anos ou mais de idade que frequentavam escola, por nível de ensino, segundo os grupos de idade, o sexo e a cor ou raça'}
27 - Censo Demográfico: {'id': '10061', 'nome': 'Pessoas de 18 anos ou mais de idade, por nível de instrução, segundo os grupos de idade, o sexo e a cor ou raça'}
27 - Censo Demográfico: {'id': '10062', 'nome': 'Número médio de anos de estudo das pessoas com 11 anos ou mais de idade, segundo os grupos de idade, o sexo e a cor ou raça'}
27 - Censo Demográfico: {'id': '10063', 'nome': 'Pessoas com nível superior completo, por áreas gerais, específicas e detalhadas de formação do curso graduação concluído, segundo os grupos de idade, o sexo e a cor ou raça'}
27 - Censo Demográfico: {'id': '10064', 'nome': 'Pessoas com nível superior completo, por áreas gerais, específicas e detalhadas de formação do curso graduação concluído, segundo os grupos de idade'}
27 - Censo Demográfico: {'id': '10065', 'nome': 'Pessoas com nível superior completo, por áreas gerais, específicas e detalhadas de formação do curso graduação concluído, segundo o sexo e a cor ou raça'}
27 - Censo Demográfico: {'id': '10066', 'nome': 'Taxa bruta de frequência escolar das pessoas indígenas, segundo os grupos de idade e o sexo'}
27 - Censo Demográfico: {'id': '10067', 'nome': 'Pessoas indígenas de até 5 anos de idade que frequentavam escola ou creche, por nível de ensino, segundo os grupos de idade e o sexo'}
27 - Censo Demográfico: {'id': '10068', 'nome': 'Pessoas indígenas de 6 a 17 anos de idade que frequentavam escola, por nível de ensino, segundo os grupos de idade e o sexo'}
27 - Censo Demográfico: {'id': '10069', 'nome': 'Pessoas indígenas de 18 anos ou mais de idade que frequentavam escola, por nível de ensino, segundo os grupos de idade e o sexo'}
27 - Censo Demográfico: {'id': '10071', 'nome': 'Pessoas indígenas de 18 anos ou mais de idade, por nível de instrução, segundo os grupos de idade e o sexo'}
27 - Censo Demográfico: {'id': '10072', 'nome': 'Número médio de anos de estudo das pessoas indígenas com 11 anos ou mais de idade, segundo os grupos de idade e o sexo'}
27 - Censo Demográfico: {'id': '10073', 'nome': 'Pessoas indígenas com nível superior completo, por áreas gerais, específicas e detalhadas de formação do curso graduação concluído, segundo os grupos de idade e o sexo'}
27 - Censo Demográfico: {'id': '10074', 'nome': 'Pessoas indígenas com nível superior completo, por áreas gerais, específicas e detalhadas de formação do curso graduação concluído, segundo o sexo'}
27 - Censo Demográfico: {'id': '10135', 'nome': 'Taxa de analfabetismo das pessoas de 15 anos ou mais de idade por grupo de idade, cor ou raça, sexo e existência de deficiência'}
27 - Censo Demográfico: {'id': '10138', 'nome': 'Estudantes de 6 anos ou mais de idade, por curso que frequentavam, grupos de idade e existência de deficiência'}
27 - Censo Demográfico: {'id': '10139', 'nome': 'Taxa de escolarização das pessoas de 6 anos ou mais de idade, por sexo, grupos de idade e existência de deficiência'}
27 - Censo Demográfico: {'id': '10140', 'nome': 'Taxa de escolarização das pessoas de 6 anos ou mais de idade, por cor ou raça, grupos de idade e existência de deficiência'}
27 - Censo Demográfico: {'id': '10141', 'nome': 'Pessoas de 25 anos ou mais de idade por sexo, nível de instrução e existência de deficiência'}
27 - Censo Demográfico: {'id': '10142', 'nome': 'Pessoas de 25 anos ou mais de idade por cor ou raça, nível de instrução e existência de deficiência'}
27 - Censo Demográfico: {'id': '10146', 'nome': 'Estudantes de 6 anos ou mais de idade, total e diagnosticados com autismo, por curso que frequentavam e grupo de idade'}
27 - Censo Demográfico: {'id': '10150', 'nome': 'Taxa de escolarização das pessoas de 6 anos ou mais de idade, total e pessoas diagnosticadas com autismo, por sexo e grupo de idade'}
27 - Censo Demográfico: {'id': '10151', 'nome': 'Taxa de escolarização das pessoas de 6 anos ou mais de idade, total e pessoas diagnosticadas com autismo, por cor ou raça e grupo de idade'}
27 - Censo Demográfico: {'id': '10153', 'nome': 'Pessoas de 25 anos ou mais de idade, total e diagnosticadas com autismo, por sexo e nível de instrução'}
27 - Censo Demográfico: {'id': '10164', 'nome': 'Taxa de analfabetismo das pessoas indígenas de 15 anos ou mais de idade por grupo de idade, sexo e existência de deficiência'}
27 - Censo Demográfico: {'id': '10165', 'nome': 'Estudantes indígenas de 6 anos ou mais de idade, por grupos de idade e existência de deficiência'}
27 - Censo Demográfico: {'id': '10166', 'nome': 'Taxa de escolarização das pessoas indígenas de 6 anos ou mais de idade, por grupos de idade e existência de deficiência'}
27 - Censo Demográfico: {'id': '10167', 'nome': 'Pessoas indígenas de 25 anos ou mais de idade por nível de instrução e existência de deficiência'}
27 - Censo Demográfico: {'id': '10170', 'nome': 'Taxa de escolarização das pessoas indígenas de 6 anos ou mais de idade, total e pessoas diagnosticadas com autismo, por grupo de idade'}
27 - Censo Demográfico: {'id': '1383', 'nome': 'Taxa de alfabetização das pessoas de 10 anos ou mais de idade por sexo'}
27 - Censo Demográfico: {'id': '1390', 'nome': 'Pessoas de 10 anos ou mais de idade, por situação do domicílio e sexo, segundo a condição de alfabetização e as classes de rendimento nominal mensal'}
27 - Censo Demográfico: {'id': '1393', 'nome': 'Pessoas de 10 anos ou mais de idade, residentes em domicílios particulares, cuja condição no domicílio não era pensionista, nem empregado(a) doméstico(a) ou seu parente, por condição de alfabetização e situação do domicílio, segundo o sexo e as classes de rendimento nominal mensal domiciliar per capita'}
27 - Censo Demográfico: {'id': '141', 'nome': 'Pessoas de 5 anos ou mais por grupos de idade, cor ou raça, alfabetização e sexo'}
27 - Censo Demográfico: {'id': '142', 'nome': 'Pessoas de 5 anos ou mais por grupos de idade, anos de estudo, sexo e situação'}
27 - Censo Demográfico: {'id': '143', 'nome': 'Pessoas de 5 anos ou mais por grupos de idade, anos de estudo, cor ou raça e sexo'}
27 - Censo Demográfico: {'id': '144', 'nome': 'Estudantes de 5 anos ou mais por grau e série que frequentavam e grupos de idade'}
27 - Censo Demográfico: {'id': '145', 'nome': 'Pessoas de 10 anos ou mais com pelo menos um curso completo por grupos de idade, grau do curso completo mais elevado, sexo e situação'}
27 - Censo Demográfico: {'id': '146', 'nome': 'Pessoas de 10 anos ou mais de idade por grupos de anos de estudo'}
27 - Censo Demográfico: {'id': '148', 'nome': 'Estudantes de 5 anos ou mais por grau e série que frequentavam'}
27 - Censo Demográfico: {'id': '1519', 'nome': 'População residente de 5 anos ou mais de idade por situação do domicílio, alfabetização e grupos de idade'}
27 - Censo Demográfico: {'id': '1520', 'nome': 'População residente de 5 anos ou mais de idade por sexo, alfabetização e grupos de idade'}
27 - Censo Demográfico: {'id': '1521', 'nome': 'População residente de 10 anos ou mais de idade por situação do domicílio, sexo, alfabetização e relação com a pessoa responsável pelo domicílio'}
27 - Censo Demográfico: {'id': '1547', 'nome': 'População residente, por frequência à escola ou creche e rede de ensino que frequentavam - Resultados Gerais da Amostra'}
27 - Censo Demográfico: {'id': '1549', 'nome': 'População residente, total e a que frequentava escola ou creche, por grupos de idade - Resultados Gerais da Amostra'}
27 - Censo Demográfico: {'id': '1551', 'nome': 'Pessoas que frequentavam escola ou creche, por curso que frequentavam - Resultados Gerais da Amostra'}
27 - Censo Demográfico: {'id': '1553', 'nome': 'População residente de 5 anos ou mais de idade por situação do domicílio, sexo, alfabetização e grupos de idade'}
27 - Censo Demográfico: {'id': '1554', 'nome': 'Pessoas de 10 anos ou mais de idade, por nível de instrução - Resultados Gerais da Amostra'}
27 - Censo Demográfico: {'id': '1699', 'nome': 'Pessoas de 10 anos ou mais de idade, total, alfabetizadas e Taxa de alfabetização por sexo'}
27 - Censo Demográfico: {'id': '1972', 'nome': 'Pessoas que frequentavam creche ou escola por nível e rede de ensino'}
27 - Censo Demográfico: {'id': '1973', 'nome': 'Pessoas que frequentavam creche ou escola por nível de ensino, sexo e grupos de idade'}
27 - Censo Demográfico: {'id': '1974', 'nome': 'Pessoas de 5 anos ou mais de idade por grupos de anos de estudo, sexo e grupos de idade'}
27 - Censo Demográfico: {'id': '201', 'nome': 'População residente de 5 anos ou mais por alfabetização, situação e grupos de idade'}
27 - Censo Demográfico: {'id': '203', 'nome': 'População residente de 5 anos ou mais por alfabetização e situação'}
27 - Censo Demográfico: {'id': '204', 'nome': 'População residente de 5 anos ou mais por alfabetização e grupos de idade'}
27 - Censo Demográfico: {'id': '2096', 'nome': 'População residente por cor ou raça, frequência à creche ou escola e grupos de idade'}
27 - Censo Demográfico: {'id': '2097', 'nome': 'Pessoas de 15 anos ou mais de idade por cor ou raça, sexo e anos de estudo'}
27 - Censo Demográfico: {'id': '2903', 'nome': 'Pessoas de 10 anos ou mais de idade por grupos de anos de estudo, sexo e classes de rendimento nominal mensal'}
27 - Censo Demográfico: {'id': '2972', 'nome': 'Pessoas de 5 anos ou mais de idade por cor e raça, sexo, alfabetização e grupos de idade'}
27 - Censo Demográfico: {'id': '2973', 'nome': 'Pessoas de 5 anos ou mais de idade por cor e raça, situação do domicílio, alfabetização e grupos de idade'}
27 - Censo Demográfico: {'id': '2974', 'nome': 'População residente por cor ou raça, frequência à creche ou escola e grupo de idade'}
27 - Censo Demográfico: {'id': '2975', 'nome': 'Pessoas residentes em domicílios particulares por grupos de idade, frequência à creche ou escola e classes de rendimento nominal médio mensal familiar per capita'}
27 - Censo Demográfico: {'id': '2976', 'nome': 'Pessoas que frequentavam creche ou escola por nível de ensino, situação do domicílio e grupos de idade'}
27 - Censo Demográfico: {'id': '2977', 'nome': 'Pessoas que frequentavam creche ou escola por nível de ensino, cor ou raça e grupos de idade'}
27 - Censo Demográfico: {'id': '2978', 'nome': 'Pessoas de 7 anos ou mais de idade por grupos de anos de estudo, sexo e grupos de idade'}
27 - Censo Demográfico: {'id': '2979', 'nome': 'Pessoas de 7 anos ou mais de idade por grupos de anos de estudo, situação do domicílio e grupos de idade'}
27 - Censo Demográfico: {'id': '2980', 'nome': 'Pessoas de 10 anos ou mais de idade por grupos de anos de estudo, cor ou raça e grupos de idade'}
27 - Censo Demográfico: {'id': '2981', 'nome': 'Pessoas de 25 anos ou mais de idade por nível educacional concluído, sexo, situação do domicílio e grupos de idade'}
27 - Censo Demográfico: {'id': '2982', 'nome': 'Pessoas de 25 anos ou mais de idade por nível educacional concluído, cor ou raça e grupos de idade'}
27 - Censo Demográfico: {'id': '2983', 'nome': 'Pessoas com curso de nível superior concluído, por nível concluído, sexo e áreas gerais, específicas e detalhadas de formação'}
27 - Censo Demográfico: {'id': '2984', 'nome': 'Pessoas com curso de nível superior concluído por cor ou raça e áreas gerais, específicas e detalhadas de formação'}
27 - Censo Demográfico: {'id': '2985', 'nome': 'População residente por grupos de idade e frequência à creche ou escola, nível de ensino e série que frequentavam'}
27 - Censo Demográfico: {'id': '2986', 'nome': 'Pessoas de 10 anos ou mais de idade por grupo de anos de estudo'}
27 - Censo Demográfico: {'id': '2987', 'nome': 'Pessoas de 10 anos ou mais de idade, total, alfabetizadas e taxa de alfabetização por grupos de idade'}
27 - Censo Demográfico: {'id': '3213', 'nome': 'Pessoas de 5 anos ou mais de idade alfabetizadas e Taxa de alfabetização das pessoas de 5 anos ou mais de idade, por idade'}
27 - Censo Demográfico: {'id': '3214', 'nome': 'Pessoas de 5 anos ou mais de idade, residentes em domicílios particulares, cuja condição no domicílio não era pensionista, nem empregado(a) doméstico(a) ou seu parente, por classes de rendimento nominal mensal domiciliar per capita, segundo a condição de alfabetização e a idade'}
27 - Censo Demográfico: {'id': '3215', 'nome': 'Pessoas de 10 anos ou mais de idade, por alfabetização e sexo, segundo a situação do domicílio e a condição no domicílio'}
27 - Censo Demográfico: {'id': '3324', 'nome': 'Pessoas de 5 anos ou mais de idade, por situação do domicílio, condição de alfabetização e sexo, segundo a idade'}
27 - Censo Demográfico: {'id': '3331', 'nome': 'População residente, por frequência à escola ou creche e rede de ensino que frequentavam'}
27 - Censo Demográfico: {'id': '3332', 'nome': 'População residente, total e a que frequentava escola ou creche, por grupos de idade'}
27 - Censo Demográfico: {'id': '3333', 'nome': 'Pessoas que frequentavam escola ou creche, por curso que frequentavam'}
27 - Censo Demográfico: {'id': '3334', 'nome': 'Pessoas de 10 anos ou mais de idade, por nível de instrução'}
27 - Censo Demográfico: {'id': '3533', 'nome': 'População residente, por situação do domicílio e frequência à escola ou creche, segundo o sexo, a cor ou raça e os grupos de idade'}
27 - Censo Demográfico: {'id': '3535', 'nome': 'Pessoas residentes em domicílios particulares, exclusive as cuja condição no domicílio era pensionista, empregado(a) doméstico(a) ou parente do(a) empregado(a) doméstico(a), por classes de rendimento nominal mensal domiciliar per capita, segundo a frequência à escola ou creche'}
27 - Censo Demográfico: {'id': '3536', 'nome': 'Pessoas que frequentavam creche ou escola, por situação do domicílio e rede de ensino, segundo o sexo, a cor ou raça, o curso que frequentavam e os grupos de idade'}
27 - Censo Demográfico: {'id': '3537', 'nome': 'Pessoas residentes em domicílios particulares, que frequentavam escola ou creche, exclusive as cuja condição no domicílio era pensionista, empregado(a) doméstico(a) ou parente do(a) empregado(a) doméstico(a), por classes de rendimento nominal mensal domiciliar per capita, segundo a rede de ensino e o curso que frequentavam'}
27 - Censo Demográfico: {'id': '3538', 'nome': 'Pessoas que frequentavam curso superior de graduação, por conclusão de outro curso superior de graduação, segundo o sexo, os grupos de idade, a rede de ensino que frequentavam e a situação de ocupação na semana de referência'}
27 - Censo Demográfico: {'id': '3539', 'nome': 'Pessoas de 10 anos ou mais de idade, por frequência à escola e situação de ocupação na semana de referência, segundo o sexo, e os grupos de idade'}
27 - Censo Demográfico: {'id': '3540', 'nome': 'Pessoas de 10 anos ou mais de idade, por nível de instrução, segundo a situação do domicílio, o sexo, a cor ou raça e os grupos de idade'}
27 - Censo Demográfico: {'id': '3541', 'nome': 'Pessoas de 25 anos ou mais de idade, residentes em domicílios particulares, por nível de instrução, segundo a situação do domicílio, o sexo e a condição no domicílio e o compartilhamento da responsabilidade pelo domicílio'}
27 - Censo Demográfico: {'id': '3542', 'nome': 'Pessoas de 15 anos ou mais de idade, residentes em domicílios particulares, exclusive as cuja condição no domicílio era pensionista, empregado(a) doméstico(a) ou parente do(a) empregado(a) doméstico(a), por nível de instrução, segundo os grupos de idade e as classes de rendimento nominal mensal domiciliar per capita'}
27 - Censo Demográfico: {'id': '3543', 'nome': 'Pessoas com pelo menos nível superior de graduação concluído, por nível de instrução mais elevado concluído, segundo o sexo e as áreas gerais, específicas e detalhadas de formação do curso de nível mais elevado consluído'}
27 - Censo Demográfico: {'id': '3544', 'nome': 'População residente, por grupos de idade, segundo a frequência à escola ou creche e curso e série que frequentavam'}
27 - Censo Demográfico: {'id': '3545', 'nome': 'Pessoas de 10 anos ou mais de idade, que frequentavam escola, por grupos de idade, segundo a situação de ocupação na semana de referência e o curso que frequentavam'}
27 - Censo Demográfico: {'id': '3546', 'nome': 'Pessoas que frequentavam e Pessoas que não frequentavam escola ou creche, por grupos de idade'}
27 - Censo Demográfico: {'id': '3547', 'nome': 'Pessoas de 25 anos ou mais de idade, por sexo e nível de instrução'}
27 - Censo Demográfico: {'id': '3987', 'nome': 'População residente, por frequência à escola ou creche e rede de ensino que frequentavam e tipo do setor - Resultados Gerais da Amostra'}
27 - Censo Demográfico: {'id': '3988', 'nome': 'População residente, total e a que frequentava escola ou creche, por grupos de idade e tipo do setor - Resultados Gerais da Amostra'}
27 - Censo Demográfico: {'id': '3989', 'nome': 'Pessoas que frequentavam escola ou creche, por curso que frequentavam e tipo do setor - Resultados Gerais da Amostra'}
27 - Censo Demográfico: {'id': '3990', 'nome': 'Pessoas de 10 anos ou mais de idade, por nível de instrução e tipo do setor - Resultados Gerais da Amostra'}
27 - Censo Demográfico: {'id': '9542', 'nome': 'Pessoas de 15 anos ou mais de idade, total e as alfabetizadas, por sexo, cor ou raça e grupos de idade'}
27 - Censo Demográfico: {'id': '9543', 'nome': 'Taxa de alfabetização das pessoas de 15 anos ou mais de idade por sexo, cor ou raça e grupos de idade'}
27 - Censo Demográfico: {'id': '9792', 'nome': 'População total e quilombola de 15 anos ou mais de idade, por alfabetização, sexo, idade e localização do domicílio'}
27 - Censo Demográfico: {'id': '9793', 'nome': 'Taxa de alfabetização da população total e quilombola de 15 anos ou mais de idade, por sexo, idade e localização do domicílio'}
27 - Censo Demográfico: {'id': '9794', 'nome': 'População de 15 anos ou mais de idade residente em territórios quilombolas, total e quilombola, por alfabetização, sexo e idade, segundo os Territórios Quilombolas'}
27 - Censo Demográfico: {'id': '9795', 'nome': 'Taxa de alfabetização da população de 15 anos ou mais de idade residente em territórios quilombolas, total e quilombola, por sexo e idade, segundo os Territórios Quilombolas'}
27 - Censo Demográfico: {'id': '9886', 'nome': 'Pessoas de 15 anos ou mais de idade residentes em favelas e comunidades urbanas, por alfabetização, cor ou raça, sexo e grupos de idade, segundo as Favelas e Comunidades Urbanas'}
27 - Contagem da População : {'id': '473', 'nome': 'Pessoas de 4 anos ou mais de idade por grupos de idade, anos de estudo, sexo e situação'}
27 - Contagem da População : {'id': '476', 'nome': 'Pessoas de 4 anos ou mais de idade por frequência à escola, grau e série, grupos de idade e sexo'}

In [168]:
assunto = 302
dados = consulta_assunto(assunto)
print_assuntos(dados)

302 - Objetivos de Desenvolvimento Sustentável: {'id': '10422', 'nome': 'Indicador 4.1.2 - Taxas de conclusão de nível de ensino, por grupos de idade e nivel de ensino e por sexo'}
302 - Objetivos de Desenvolvimento Sustentável: {'id': '4731', 'nome': 'Indicador 4.1.2 - Taxas de conclusão de nível de ensino, por grupos de idade e nível de ensino'}
302 - Objetivos de Desenvolvimento Sustentável: {'id': '4734', 'nome': 'Indicador 4.2.2 - Taxa de participação das pessoas de 5 anos de idade no ensino organizado, por sexo'}
302 - Objetivos de Desenvolvimento Sustentável: {'id': '4735', 'nome': 'Indicador 4.5.1A - Índices de paridade das taxas de conclusão de nível de ensino, por tipo de índice de paridade e grupos de idade e nível de ensino'}
302 - Objetivos de Desenvolvimento Sustentável: {'id': '4736', 'nome': 'Indicador 4.5.1B - Índices de paridade da taxa de participação das pessoas de 5 anos de idade no ensino organizado, por tipo de índice de paridade'}
302 - Objetivos de Desenvolvimento Sustentável: {'id': '6676', 'nome': 'Indicador 4.c.1 - Docentes, total, com formação adequada e proporção, por sexo e etapa de ensino'}
302 - Objetivos de Desenvolvimento Sustentável: {'id': '9908', 'nome': 'Indicador 4.2.2 - Taxa de participação das pessoas de 5 anos de idade no ensino organizado, por cor ou raça'}
302 - Objetivos de Desenvolvimento Sustentável: {'id': '9910', 'nome': 'Indicador 4.1.2 - Taxas de conclusão de nível de ensino, por grupos de idade e nivel de ensino e por cor ou raça'}

In [169]:
assunto = 235
dados = consulta_assunto(assunto)
print_assuntos(dados)

235 - Indicadores de Desenvolvimento Sustentável: {'id': '3836', 'nome': 'Taxa de frequência escolar bruta e Taxa de frequência escolar líquida'}
235 - Indicadores de Desenvolvimento Sustentável: {'id': '3837', 'nome': 'Taxa de frequência escolar bruta e Taxa de frequência escolar líquida, por sexo'}
235 - Indicadores de Desenvolvimento Sustentável: {'id': '3838', 'nome': 'Taxa de frequência escolar bruta e Taxa de frequência escolar líquida, por cor ou raça'}

In [170]:
assunto = 179
dados = consulta_assunto(assunto)
print_assuntos(dados)

179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '1856', 'nome': 'Estudantes de 5 anos ou mais de idade, por situação, sexo e grau e série que frequentavam'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '1858', 'nome': 'Estudantes de 5 anos ou mais de idade, por grau e série que frequentavam, sexo e grupos de idade'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '2388', 'nome': 'Pessoas que frequentavam creche ou escola, por grau e série que frequentavam e rede de ensino'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '2389', 'nome': 'Pessoas que frequentavam creche ou escola, por grau e série que frequentavam, sexo e grupos de idade'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '271', 'nome': 'Pessoas de 5 anos ou mais de idade, por situação, sexo, alfabetização e grupos de idade'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '272', 'nome': 'Pessoas de 10 anos ou mais de idade, por situação, sexo e anos de estudo'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '2858', 'nome': 'Pessoas de 5 anos ou mais de idade, por situação, sexo e alfabetização'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '2893', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola, por grau e a série que frequentavam e rede de ensino'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '2900', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola, por grau e serie que frequentavam, sexo e grupos de idade'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '2916', 'nome': 'Pessoas de 0 a 17 anos de idade, por situação do domicílio e frequência à creche ou escola'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '2918', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola, por grupos de idade'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '2919', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola (exceto de nível superior), por nível de ensino e rede de ensino que frequentavam'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '2920', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola (exceto de nível superior), por nível de ensino e tempo de permanência diária na creche ou escola'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '2921', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola (exceto de nível superior), por rede de ensino que frequentavam e oferta gratuita de merenda escolar ou outra refeição pela creche ou escola'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '2922', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola (exceto de nível superior), por nível de ensino e consumo de merenda escolar ou outra refeição gratuita'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '2923', 'nome': 'Pessoas de 0 a 17 anos de idade que não frequentavam creche ou escola, por motivo de não frequentarem creche ou escola'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '356', 'nome': 'Número médio de anos de estudo das pessoas de 10 anos ou mais de idade, total e ocupadas na semana de referência, por situação, sexo e grupos de idade'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '357', 'nome': 'Estudantes de 5 anos ou mais de idade, por situação, sexo, grupos de idade, grau e série que frequentavam e rede de ensino'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '867', 'nome': 'Pessoas de 0 a 17 anos de idade, por frequência à creche ou escola'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '868', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola, por nível de ensino, sexo e grupos de idade'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '869', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola, mas não compareceram pelo menos um dia no período de referência de 60 dias, por principal motivo de não terem comparecido à creche ou escola e grupos de idade'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '870', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola, por nível de ensino e rede de ensino que frequentavam'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '871', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola, por nível de ensino e tempo de permanência diária na creche ou escola'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '872', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola, por rede de ensino que frequentavam e oferta gratuita de merenda escolar ou outra refeição pela creche ou escola'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '873', 'nome': 'Pessoas de 0 a 17 anos de idade que frequentavam creche ou escola, por nível de ensino e consumo de merenda escolar ou outra refeição gratuita'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '983', 'nome': 'Estudantes de 4 anos ou mais de idade, por rede de ensino que frequentavam, sexo, o nível de ensino, a duração do ensino fundamental e a série que frequentavam'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '984', 'nome': 'Pessoas que frequentavam creche ou escola, por nível de ensino e rede de ensino que frequentavam, sexo e grupos de idade'}
179 - Pesquisa Nacional por Amostra de Domicílios: {'id': '985', 'nome': 'Estudantes do ensino fundamental, de 5 anos ou mais de idade, por duração do ensino fundamental, série e rede de ensino que frequentavam, sexo e grupos de idades'}

# Indicadores escolhidos:

**📚 Acesso à educação**

* 7138 — escolarização por sexo
* 7139 — escolarização por cor/raça

**📖 Alfabetização**
* 1187 — alfabetização por sexo
* 1188 — alfabetização por cor/raça

**🎓 Frequência escolar**
* 7141 — frequência líquida ajustada por sexo
* 7142 — frequência líquida ajustada por cor/raça

**🏫 Conclusão**
* 10422 — conclusão por sexo
* 9910 — conclusão por cor/raça

In [232]:
def verificar_metadados(agregado):
  url = f'https://servicodados.ibge.gov.br/api/v3/agregados/{agregado}/metadados'
  response = requests.get(url)
  response.raise_for_status()
  dados = response.json()
  return dados

def print_metadados(dados):
  for linha in dados:
    if linha != 'classificacoes':
      print(f'{linha}: {dados[linha]}')
    else:
      for classificacao in dados[linha]:
        for categorias in classificacao['categorias']:
          print(f"classificacoes: {classificacao['id']} - {classificacao['nome']}: {categorias}")

**7138 — escolarização por sexo**

In [392]:
agregado = 7138
metadados = verificar_metadados(agregado)
print_metadados(metadados)

id: 7138
nome: Taxa de escolarização, por sexo e grupo de idade
URL: https://sidra.ibge.gov.br/tabela/7138
pesquisa: Pesquisa Nacional por Amostra de Domicílios Contínua anual
assunto: Educação
periodicidade: {'frequencia': 'anual', 'inicio': 2016, 'fim': 2025}
nivelTerritorial: {'Administrativo': ['N1', 'N2', 'N6', 'N14', 'N7', 'N3'], 'Especial': [], 'IBGE': []}
variaveis: [{'id': 10276, 'nome': 'Taxa de escolarização', 'unidade': '%', 'sumarizacao': []}, {'id': 10277, 'nome': 'Coeficiente de variação - Taxa de escolarização', 'unidade': '%', 'sumarizacao': []}]
classificacoes: 2 - Sexo: {'id': 6794, 'nome': 'Total', 'unidade': None, 'nivel': 0}
classificacoes: 2 - Sexo: {'id': 4, 'nome': 'Homens', 'unidade': None, 'nivel': 1}
classificacoes: 2 - Sexo: {'id': 5, 'nome': 'Mulheres', 'unidade': None, 'nivel': 1}
classificacoes: 58 - Grupo de idade: {'id': 95253, 'nome': 'Total', 'unidade': None, 'nivel': 0}
classificacoes: 58 - Grupo de idade: {'id': 41126, 'nome': '0 a 5 anos', 'unidade': None, 'nivel': 1}
classificacoes: 58 - Grupo de idade: {'id': 99749, 'nome': '0 a 3 anos', 'unidade': None, 'nivel': 2}
classificacoes: 58 - Grupo de idade: {'id': 47813, 'nome': '4 a 5 anos', 'unidade': None, 'nivel': 2}
classificacoes: 58 - Grupo de idade: {'id': 31615, 'nome': '6 a 14 anos', 'unidade': None, 'nivel': 1}
classificacoes: 58 - Grupo de idade: {'id': 2792, 'nome': '15 a 17 anos', 'unidade': None, 'nivel': 1}
classificacoes: 58 - Grupo de idade: {'id': 100052, 'nome': '18 a 24 anos', 'unidade': None, 'nivel': 1}
classificacoes: 58 - Grupo de idade: {'id': 108866, 'nome': '25 anos ou mais', 'unidade': None, 'nivel': 1}

In [393]:
ano = metadados['periodicidade']['fim']
variavel = metadados['variaveis'][0]['id']

params = {
    "localidades": "N3[all]",
    "classificacao": "2[6794,4,5]|58[95253,41126,99749,47813,31615,2792,100052,108866]"
}

url = f"https://servicodados.ibge.gov.br/api/v3/agregados/{agregado}/periodos/{ano}/variaveis/{variavel}"
resp = requests.get(url, params=params, timeout=20)
resp.raise_for_status()
dados = resp.json()

In [394]:
for linha in dados[0]['resultados']:
  print(linha)

{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '58', 'nome': 'Grupo de idade', 'categoria': {'95253': 'Total'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '27.6'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '32.4'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '32.1'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '33.1'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '31.6'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '29.1'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '30.9'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '30.4'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '28.6'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '27.0'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '26.1'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '28.5'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '27.0'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '30.4'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '28.6'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '27.6'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '25.2'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '26.5'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '26.2'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '25.5'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '27.2'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '26.7'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '25.9'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '28.5'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '29.5'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '26.6'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '32.0'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '58', 'nome': 'Grupo de idade', 'categoria': {'41126': '0 a 5 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '47.1'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '40.3'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '45.3'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '45.3'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '48.7'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '26.6'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '61.3'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '60.2'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '60.7'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '61.4'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '59.6'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '57.6'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '56.0'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '59.5'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '58.3'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '63.7'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '59.4'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '57.3'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '61.2'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '70.0'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '64.0'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '71.7'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '60.1'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '57.0'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '55.9'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '54.5'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '59.7'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '58', 'nome': 'Grupo de idade', 'categoria': {'99749': '0 a 3 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '23.4'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '18.1'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '19.8'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '21.5'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '24.4'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '8.1'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '43.1'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '38.7'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '37.3'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '40.2'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '36.6'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '35.1'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '33.9'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '41.4'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '36.4'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '43.1'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '39.3'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '36.7'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '39.9'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '55.7'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '46.5'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '57.4'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '42.5'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '37.1'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '37.1'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '32.6'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '39.4'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '58', 'nome': 'Grupo de idade', 'categoria': {'47813': '4 a 5 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '84.9'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '80.6'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '86.5'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '91.0'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '94.1'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '60.0'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '95.6'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '98.1'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '98.2'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '98.9'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '95.7'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '94.4'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '95.4'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '95.8'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '94.5'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '97.8'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '95.6'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '92.1'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '93.9'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '96.7'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '95.4'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '94.7'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '91.8'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '92.4'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '94.2'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '92.7'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '96.3'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '58', 'nome': 'Grupo de idade', 'categoria': {'31615': '6 a 14 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '99.4'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '98.8'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '98.6'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '97.6'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '99.4'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '97.4'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '99.2'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '99.6'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '99.3'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '99.6'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '99.3'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '99.4'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '99.7'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '99.4'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '99.7'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '99.5'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '99.6'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '99.7'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '99.7'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '99.7'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '99.0'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '99.5'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '99.3'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '99.5'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '99.7'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '99.4'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '99.6'}}]}

In [395]:
print(dados[0]["resultados"][0].keys())
print(dados[0]["resultados"][0]['classificacoes'][0].keys())
print(dados[0]["resultados"][0]['series'][0].keys())

dict_keys(['classificacoes', 'series'])
dict_keys(['id', 'nome', 'categoria'])
dict_keys(['localidade', 'serie'])

In [396]:
linhas = []

for resultado in dados[0]["resultados"]:
    # ------------------------------
    # Sexo
    # ------------------------------
    sexo = resultado["classificacoes"][0]["categoria"]

    # ------------------------------
    # Grupo de idade
    # ------------------------------
    grupo_idade = resultado["classificacoes"][1]["categoria"]

    # ------------------------------
    # Localidade
    # ------------------------------
    for serie in resultado["series"]:
        estado = serie["localidade"]["nome"]

        # ------------------------------
        # Valor do último ano
        # ------------------------------
        valor = serie["serie"][str(ano)]

        # ------------------------------
        # Montando as linhas
        # ------------------------------
        linhas.append({
            "Estado": estado,
            "Sexo": list(sexo.values())[0],
            "Grupo de idade": list(grupo_idade.values())[0],
            "Taxa de escolarização (%)": valor
        })
# ==========================================
# 4. DATAFRAME
# ==========================================
df = pd.DataFrame(linhas)

# ==========================================
# 5. CONVERSÃO DO VALOR
# ==========================================
df["Taxa de escolarização (%)"] = pd.to_numeric(
    df["Taxa de escolarização (%)"],
    errors="coerce"
)

# ==========================================
# 6. ORDENAÇÃO
# ==========================================
df = df.sort_values(
    by=["Estado", "Sexo"]
).reset_index(drop=True)

# ==========================================
# 7. VISUALIZAÇÃO
# ==========================================
print("\nQuantidade de linhas:", len(df))
print("\nEstados encontrados:", df["Estado"].nunique())
df

Quantidade de linhas: 648

Estados encontrados: 27

        Estado    Sexo   Grupo de idade  Taxa de escolarização (%)
0         Acre  Homens            Total                       31.7
1         Acre  Homens       0 a 5 anos                       38.6
2         Acre  Homens       0 a 3 anos                       17.2
3         Acre  Homens       4 a 5 anos                       79.6
4         Acre  Homens      6 a 14 anos                       98.6
..         ...     ...              ...                        ...
643  Tocantins   Total       4 a 5 anos                       95.6
644  Tocantins   Total      6 a 14 anos                       99.2
645  Tocantins   Total     15 a 17 anos                       93.2
646  Tocantins   Total     18 a 24 anos                       35.8
647  Tocantins   Total  25 anos ou mais                        5.9

[648 rows x 4 columns]

In [397]:
regioes = {
        "Acre": "Norte",
        "Alagoas": "Nordeste",
        "Amapá": "Norte",
        "Amazonas": "Norte",
        "Bahia": "Nordeste",
        "Ceará": "Nordeste",
        "Distrito Federal": "Centro-Oeste",
        "Espírito Santo": "Sudeste",
        "Goiás": "Centro-Oeste",
        "Maranhão": "Nordeste",
        "Mato Grosso": "Centro-Oeste",
        "Mato Grosso do Sul": "Centro-Oeste",
        "Minas Gerais": "Sudeste",
        "Pará": "Norte",
        "Paraíba": "Nordeste",
        "Paraná": "Sul",
        "Pernambuco": "Nordeste",
        "Piauí": "Nordeste",
        "Rio de Janeiro": "Sudeste",
        "Rio Grande do Norte": "Nordeste",
        "Rio Grande do Sul": "Sul",
        "Rondônia": "Norte",
        "Roraima": "Norte",
        "Santa Catarina": "Sul",
        "São Paulo": "Sudeste",
        "Sergipe": "Nordeste",
        "Tocantins": "Norte",
    }

df['Região'] = df['Estado'].map(regioes)
df

        Estado    Sexo   Grupo de idade  Taxa de escolarização (%) Região
0         Acre  Homens            Total                       31.7  Norte
1         Acre  Homens       0 a 5 anos                       38.6  Norte
2         Acre  Homens       0 a 3 anos                       17.2  Norte
3         Acre  Homens       4 a 5 anos                       79.6  Norte
4         Acre  Homens      6 a 14 anos                       98.6  Norte
..         ...     ...              ...                        ...    ...
643  Tocantins   Total       4 a 5 anos                       95.6  Norte
644  Tocantins   Total      6 a 14 anos                       99.2  Norte
645  Tocantins   Total     15 a 17 anos                       93.2  Norte
646  Tocantins   Total     18 a 24 anos                       35.8  Norte
647  Tocantins   Total  25 anos ou mais                        5.9  Norte

[648 rows x 5 columns]

**7139 — escolarização por cor/raça**

In [295]:
agregado = 7139
metadados = verificar_metadados(agregado)
print_metadados(metadados)

id: 7139
nome: Taxa de escolarização, por cor ou raça e grupo de idade
URL: https://sidra.ibge.gov.br/tabela/7139
pesquisa: Pesquisa Nacional por Amostra de Domicílios Contínua anual
assunto: Educação
periodicidade: {'frequencia': 'anual', 'inicio': 2016, 'fim': 2025}
nivelTerritorial: {'Administrativo': ['N1', 'N2', 'N14', 'N7', 'N3'], 'Especial': [], 'IBGE': []}
variaveis: [{'id': 10276, 'nome': 'Taxa de escolarização', 'unidade': '%', 'sumarizacao': []}, {'id': 10277, 'nome': 'Coeficiente de variação - Taxa de escolarização', 'unidade': '%', 'sumarizacao': []}]
classificacoes: 86 - Cor ou raça: {'id': 95251, 'nome': 'Total', 'unidade': None, 'nivel': 0}
classificacoes: 86 - Cor ou raça: {'id': 2776, 'nome': 'Branca', 'unidade': None, 'nivel': 1}
classificacoes: 86 - Cor ou raça: {'id': 119525, 'nome': 'Preta ou parda', 'unidade': None, 'nivel': 1}
classificacoes: 58 - Grupo de idade: {'id': 95253, 'nome': 'Total', 'unidade': None, 'nivel': 0}
classificacoes: 58 - Grupo de idade: {'id': 41126, 'nome': '0 a 5 anos', 'unidade': None, 'nivel': 1}
classificacoes: 58 - Grupo de idade: {'id': 99749, 'nome': '0 a 3 anos', 'unidade': None, 'nivel': 2}
classificacoes: 58 - Grupo de idade: {'id': 47813, 'nome': '4 a 5 anos', 'unidade': None, 'nivel': 2}
classificacoes: 58 - Grupo de idade: {'id': 31615, 'nome': '6 a 14 anos', 'unidade': None, 'nivel': 1}
classificacoes: 58 - Grupo de idade: {'id': 2792, 'nome': '15 a 17 anos', 'unidade': None, 'nivel': 1}
classificacoes: 58 - Grupo de idade: {'id': 100052, 'nome': '18 a 24 anos', 'unidade': None, 'nivel': 1}
classificacoes: 58 - Grupo de idade: {'id': 108866, 'nome': '25 anos ou mais', 'unidade': None, 'nivel': 1}

In [297]:
ano = metadados['periodicidade']['fim']
variavel = metadados['variaveis'][0]['id']

params = {
    "localidades": "N3[all]",
    "classificacao": "86[95251,2776,119525]|58[95253,41126,99749,47813,31615,2792,100052,108866]"
}

url = f"https://servicodados.ibge.gov.br/api/v3/agregados/{agregado}/periodos/{ano}/variaveis/{variavel}"
resp = requests.get(url, params=params, timeout=20)
resp.raise_for_status()
dados = resp.json()

In [298]:
for linha in dados[0]['resultados']:
  print(linha)

{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '58', 'nome': 'Grupo de idade', 'categoria': {'95253': 'Total'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '27.6'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '32.4'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '32.1'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '33.1'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '31.6'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '29.1'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '30.9'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '30.4'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '28.6'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '27.0'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '26.1'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '28.5'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '27.0'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '30.4'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '28.6'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '27.6'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '25.2'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '26.5'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '26.2'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '25.5'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '27.2'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '26.7'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '25.9'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '28.5'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '29.5'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '26.6'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '32.0'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '58', 'nome': 'Grupo de idade', 'categoria': {'41126': '0 a 5 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '47.1'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '40.3'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '45.3'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '45.3'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '48.7'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '26.6'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '61.3'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '60.2'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '60.7'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '61.4'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '59.6'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '57.6'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '56.0'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '59.5'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '58.3'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '63.7'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '59.4'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '57.3'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '61.2'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '70.0'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '64.0'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '71.7'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '60.1'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '57.0'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '55.9'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '54.5'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '59.7'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '58', 'nome': 'Grupo de idade', 'categoria': {'99749': '0 a 3 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '23.4'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '18.1'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '19.8'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '21.5'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '24.4'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '8.1'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '43.1'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '38.7'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '37.3'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '40.2'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '36.6'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '35.1'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '33.9'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '41.4'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '36.4'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '43.1'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '39.3'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '36.7'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '39.9'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '55.7'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '46.5'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '57.4'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '42.5'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '37.1'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '37.1'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '32.6'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '39.4'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '58', 'nome': 'Grupo de idade', 'categoria': {'47813': '4 a 5 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '84.9'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '80.6'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '86.5'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '91.0'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '94.1'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '60.0'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '95.6'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '98.1'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '98.2'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '98.9'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '95.7'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '94.4'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '95.4'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '95.8'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '94.5'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '97.8'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '95.6'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '92.1'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '93.9'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '96.7'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '95.4'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '94.7'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '91.8'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '92.4'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '94.2'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '92.7'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '96.3'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '58', 'nome': 'Grupo de idade', 'categoria': {'31615': '6 a 14 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '99.4'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '98.8'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '98.6'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '97.6'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '99.4'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '97.4'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '99.2'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '99.6'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '99.3'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '99.6'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '99.3'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '99.4'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '99.7'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '99.4'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '99.7'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '99.5'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '99.6'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '99.7'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '99.7'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '99.7'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '99.0'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '99.5'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '99.3'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '99.5'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '99.7'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '99.4'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '99.6'}}]}

In [299]:
print(dados[0]["resultados"][0].keys())
print(dados[0]["resultados"][0]['classificacoes'][0].keys())
print(dados[0]["resultados"][0]['series'][0].keys())

dict_keys(['classificacoes', 'series'])
dict_keys(['id', 'nome', 'categoria'])
dict_keys(['localidade', 'serie'])

In [301]:
linhas = []

for resultado in dados[0]["resultados"]:
    # ------------------------------
    # Cor
    # ------------------------------
    cor = resultado["classificacoes"][0]["categoria"]

    # ------------------------------
    # Grupo de idade
    # ------------------------------
    grupo_idade = resultado["classificacoes"][1]["categoria"]

    # ------------------------------
    # Localidade
    # ------------------------------
    for serie in resultado["series"]:
        estado = serie["localidade"]["nome"]

        # ------------------------------
        # Valor do último ano
        # ------------------------------
        valor = serie["serie"][str(ano)]

        # ------------------------------
        # Montando as linhas
        # ------------------------------
        linhas.append({
            "Estado": estado,
            "Cor/Raça": list(cor.values())[0],
            "Grupo de idade": list(grupo_idade.values())[0],
            "Taxa de escolarização (%)": valor
        })
# ==========================================
# 4. DATAFRAME
# ==========================================
df = pd.DataFrame(linhas)

# ==========================================
# 5. CONVERSÃO DO VALOR
# ==========================================
df["Taxa de escolarização (%)"] = pd.to_numeric(
    df["Taxa de escolarização (%)"],
    errors="coerce"
)

# ==========================================
# 6. ORDENAÇÃO
# ==========================================
df = df.sort_values(
    by=["Estado", "Cor/Raça"]
).reset_index(drop=True)

# ==========================================
# 7. VISUALIZAÇÃO
# ==========================================
print("\nQuantidade de linhas:", len(df))
print("\nEstados encontrados:", df["Estado"].nunique())
df

Quantidade de linhas: 648

Estados encontrados: 27

        Estado Cor/Raça   Grupo de idade  Taxa de escolarização (%)
0         Acre   Branca            Total                       35.2
1         Acre   Branca       0 a 5 anos                       36.8
2         Acre   Branca       0 a 3 anos                       13.5
3         Acre   Branca       4 a 5 anos                       86.6
4         Acre   Branca      6 a 14 anos                       99.7
..         ...      ...              ...                        ...
643  Tocantins    Total       4 a 5 anos                       95.6
644  Tocantins    Total      6 a 14 anos                       99.2
645  Tocantins    Total     15 a 17 anos                       93.2
646  Tocantins    Total     18 a 24 anos                       35.8
647  Tocantins    Total  25 anos ou mais                        5.9

[648 rows x 4 columns]

**1187 — alfabetização por sexo**

In [342]:
agregado = 1187
metadados = verificar_metadados(agregado)
print_metadados(metadados)

id: 1187
nome: Taxa de alfabetização das pessoas de 15 anos ou mais de idade por sexo
URL: https://sidra.ibge.gov.br/tabela/1187
pesquisa: Indicadores de Desenvolvimento Sustentável
assunto: Taxa de alfabetização
periodicidade: {'frequencia': 'anual', 'inicio': 2004, 'fim': 2015}
nivelTerritorial: {'Administrativo': ['N1', 'N2', 'N3'], 'Especial': [], 'IBGE': []}
variaveis: [{'id': 2513, 'nome': 'Taxa de alfabetização das pessoas de 15 anos ou mais de idade', 'unidade': '%', 'sumarizacao': []}]
classificacoes: 2 - Sexo: {'id': 6794, 'nome': 'Total', 'unidade': None, 'nivel': 0}
classificacoes: 2 - Sexo: {'id': 4, 'nome': 'Homens', 'unidade': None, 'nivel': 1}
classificacoes: 2 - Sexo: {'id': 5, 'nome': 'Mulheres', 'unidade': None, 'nivel': 1}

In [347]:
ano = metadados['periodicidade']['fim']
variavel = metadados['variaveis'][0]['id']

params = {
    "localidades": "N3[all]",
    "classificacao": "2[6794,4,5]"
}

url = f"https://servicodados.ibge.gov.br/api/v3/agregados/{agregado}/periodos/{ano}/variaveis/{variavel}"
resp = requests.get(url, params=params, timeout=20)
resp.raise_for_status()
dados = resp.json()

In [348]:
for linha in dados[0]['resultados']:
  print(linha)

{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2015': '92.0'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2015': '86.2'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2015': '93.3'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2015': '92.0'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2015': '90.1'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2015': '94.1'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2015': '88.6'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2015': '81.2'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2015': '81.8'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2015': '82.7'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2015': '84.2'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2015': '82.9'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2015': '84.6'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2015': '80.0'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2015': '84.4'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2015': '86.5'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2015': '93.2'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2015': '94.0'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2015': '97.0'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2015': '96.5'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2015': '94.9'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2015': '96.5'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2015': '96.5'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2015': '94.0'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2015': '92.9'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2015': '93.9'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2015': '97.0'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'4': 'Homens'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2015': '91.6'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2015': '85.6'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2015': '93.4'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2015': '90.3'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2015': '88.8'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2015': '94.1'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2015': '87.2'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2015': '79.1'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2015': '79.6'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2015': '79.4'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2015': '81.9'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2015': '81.2'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2015': '83.4'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2015': '78.6'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2015': '82.4'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2015': '85.3'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2015': '93.7'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2015': '94.9'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2015': '97.4'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2015': '96.9'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2015': '95.7'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2015': '96.7'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2015': '96.7'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2015': '94.2'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2015': '92.2'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2015': '93.5'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2015': '97.1'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'5': 'Mulheres'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2015': '92.4'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2015': '86.9'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2015': '93.3'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2015': '93.8'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2015': '91.4'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2015': '94.2'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2015': '90.0'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2015': '83.2'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2015': '83.9'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2015': '85.7'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2015': '86.3'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2015': '84.4'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2015': '85.8'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2015': '81.2'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2015': '86.2'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2015': '87.5'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2015': '92.8'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2015': '93.3'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2015': '96.7'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2015': '96.0'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2015': '94.1'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2015': '96.2'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2015': '96.2'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2015': '93.8'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2015': '93.5'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2015': '94.3'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2015': '97.0'}}]}

In [349]:
linhas = []

for resultado in dados[0]["resultados"]:
    # ------------------------------
    # Sexo
    # ------------------------------
    sexo = resultado["classificacoes"][0]["categoria"]

    # ------------------------------
    # Localidade
    # ------------------------------
    for serie in resultado["series"]:
        estado = serie["localidade"]["nome"]

        # ------------------------------
        # Valor do último ano
        # ------------------------------
        valor = serie["serie"][str(ano)]

        # ------------------------------
        # Montando as linhas
        # ------------------------------
        linhas.append({
            "Estado": estado,
            "Sexo": list(sexo.values())[0],
            "Taxa de alfabetização das pessoas de 15 anos ou mais (%)": valor
        })
# ==========================================
# 4. DATAFRAME
# ==========================================
df = pd.DataFrame(linhas)

# ==========================================
# 5. CONVERSÃO DO VALOR
# ==========================================
df["Taxa de alfabetização das pessoas de 15 anos ou mais (%)"] = pd.to_numeric(
    df["Taxa de alfabetização das pessoas de 15 anos ou mais (%)"],
    errors="coerce"
)

# ==========================================
# 6. ORDENAÇÃO
# ==========================================
df = df.sort_values(
    by=["Estado", "Sexo"]
).reset_index(drop=True)

# ==========================================
# 7. VISUALIZAÇÃO
# ==========================================
print("\nQuantidade de linhas:", len(df))
print("\nEstados encontrados:", df["Estado"].nunique())
df

Quantidade de linhas: 81

Estados encontrados: 27

,Estado,Sexo,Taxa de alfabetização das pessoas de 15 anos ou mais (%)
0,Acre,Homens,85.6
1,Acre,Mulheres,86.9
2,Acre,Total,86.2
3,Alagoas,Homens,78.6
4,Alagoas,Mulheres,81.2
...,...,...,...
76,São Paulo,Mulheres,96.0
77,São Paulo,Total,96.5
78,Tocantins,Homens,87.2
79,Tocantins,Mulheres,90.0
80,Tocantins,Total,88.6

**1188 — alfabetização por cor/raça**

In [350]:
agregado = 1188
metadados = verificar_metadados(agregado)
print_metadados(metadados)

id: 1188
nome: Taxa de alfabetização das pessoas de 15 anos ou mais de idade, por cor ou raça
URL: https://sidra.ibge.gov.br/tabela/1188
pesquisa: Indicadores de Desenvolvimento Sustentável
assunto: Taxa de alfabetização
periodicidade: {'frequencia': 'anual', 'inicio': 2004, 'fim': 2015}
nivelTerritorial: {'Administrativo': ['N1', 'N2', 'N3'], 'Especial': [], 'IBGE': []}
variaveis: [{'id': 2513, 'nome': 'Taxa de alfabetização das pessoas de 15 anos ou mais de idade', 'unidade': '%', 'sumarizacao': []}]
classificacoes: 86 - Cor ou raça: {'id': 95251, 'nome': 'Total', 'unidade': None, 'nivel': 0}
classificacoes: 86 - Cor ou raça: {'id': 2776, 'nome': 'Branca', 'unidade': None, 'nivel': 1}
classificacoes: 86 - Cor ou raça: {'id': 119525, 'nome': 'Preta ou parda', 'unidade': None, 'nivel': 1}

In [353]:
ano = metadados['periodicidade']['fim']
variavel = metadados['variaveis'][0]['id']

params = {
    "localidades": "N3[all]",
    "classificacao": "86[95251,2776,119525]"
}

url = f"https://servicodados.ibge.gov.br/api/v3/agregados/{agregado}/periodos/{ano}/variaveis/{variavel}"
resp = requests.get(url, params=params, timeout=20)
resp.raise_for_status()
dados = resp.json()

In [354]:
for linha in dados[0]['resultados']:
  print(linha)

{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2015': '92.0'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2015': '86.2'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2015': '93.3'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2015': '92.0'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2015': '90.1'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2015': '94.1'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2015': '88.6'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2015': '81.2'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2015': '81.8'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2015': '82.7'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2015': '84.2'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2015': '82.9'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2015': '84.6'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2015': '80.0'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2015': '84.4'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2015': '86.5'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2015': '93.2'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2015': '94.0'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2015': '97.0'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2015': '96.5'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2015': '94.9'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2015': '96.5'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2015': '96.5'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2015': '94.0'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2015': '92.9'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2015': '93.9'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2015': '97.0'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'2776': 'Branca'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2015': '94.1'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2015': '88.6'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2015': '95.7'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2015': '93.9'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2015': '92.7'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2015': '95.7'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2015': '92.6'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2015': '87.0'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2015': '84.9'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2015': '85.6'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2015': '87.3'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2015': '86.4'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2015': '87.7'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2015': '83.5'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2015': '85.6'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2015': '87.6'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2015': '95.4'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2015': '95.1'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2015': '97.9'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2015': '97.3'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2015': '96.1'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2015': '97.0'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2015': '97.2'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2015': '95.8'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2015': '95.4'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2015': '95.0'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2015': '97.6'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'119525': 'Preta ou parda'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2015': '91.0'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2015': '86.3'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2015': '92.9'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2015': '91.4'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2015': '89.6'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2015': '93.6'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2015': '87.3'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2015': '79.8'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2015': '81.1'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2015': '81.5'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2015': '82.2'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2015': '81.0'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2015': '83.2'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2015': '78.6'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2015': '84.0'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2015': '86.2'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2015': '91.6'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2015': '93.2'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2015': '96.2'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2015': '95.1'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2015': '92.1'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2015': '93.2'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2015': '93.4'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2015': '92.6'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2015': '91.7'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2015': '93.2'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2015': '96.6'}}]}

In [355]:
linhas = []

for resultado in dados[0]["resultados"]:
    # ------------------------------
    # Sexo
    # ------------------------------
    cor = resultado["classificacoes"][0]["categoria"]

    # ------------------------------
    # Localidade
    # ------------------------------
    for serie in resultado["series"]:
        estado = serie["localidade"]["nome"]

        # ------------------------------
        # Valor do último ano
        # ------------------------------
        valor = serie["serie"][str(ano)]

        # ------------------------------
        # Montando as linhas
        # ------------------------------
        linhas.append({
            "Estado": estado,
            "Cor/Raça": list(cor.values())[0],
            "Taxa de alfabetização das pessoas de 15 anos ou mais (%)": valor
        })
# ==========================================
# 4. DATAFRAME
# ==========================================
df = pd.DataFrame(linhas)

# ==========================================
# 5. CONVERSÃO DO VALOR
# ==========================================
df["Taxa de alfabetização das pessoas de 15 anos ou mais (%)"] = pd.to_numeric(
    df["Taxa de alfabetização das pessoas de 15 anos ou mais (%)"],
    errors="coerce"
)

# ==========================================
# 6. ORDENAÇÃO
# ==========================================
df = df.sort_values(
    by=["Estado", "Cor/Raça"]
).reset_index(drop=True)

# ==========================================
# 7. VISUALIZAÇÃO
# ==========================================
print("\nQuantidade de linhas:", len(df))
print("\nEstados encontrados:", df["Estado"].nunique())
df

Quantidade de linhas: 81

Estados encontrados: 27

,Estado,Cor/Raça,Taxa de alfabetização das pessoas de 15 anos ou mais (%)
0,Acre,Branca,88.6
1,Acre,Preta ou parda,86.3
2,Acre,Total,86.2
3,Alagoas,Branca,83.5
4,Alagoas,Preta ou parda,78.6
...,...,...,...
76,São Paulo,Preta ou parda,95.1
77,São Paulo,Total,96.5
78,Tocantins,Branca,92.6
79,Tocantins,Preta ou parda,87.3
80,Tocantins,Total,88.6

**7141 — frequência líquida ajustada por sexo**

In [306]:
agregado = 7141
metadados = verificar_metadados(agregado)
print_metadados(metadados)

id: 7141
nome: Taxa ajustada de frequência escolar líquida, por sexo e faixa etária ideal por curso frequentado
URL: https://sidra.ibge.gov.br/tabela/7141
pesquisa: Pesquisa Nacional por Amostra de Domicílios Contínua anual
assunto: Educação
periodicidade: {'frequencia': 'anual', 'inicio': 2016, 'fim': 2025}
nivelTerritorial: {'Administrativo': ['N1', 'N2', 'N3'], 'Especial': [], 'IBGE': []}
variaveis: [{'id': 10282, 'nome': 'Taxa ajustada de frequência escolar líquida', 'unidade': '%', 'sumarizacao': []}, {'id': 10283, 'nome': 'Coeficiente de variação - Taxa ajustada de frequência escolar líquida', 'unidade': '%', 'sumarizacao': []}]
classificacoes: 2 - Sexo: {'id': 6794, 'nome': 'Total', 'unidade': None, 'nivel': 0}
classificacoes: 2 - Sexo: {'id': 4, 'nome': 'Homens', 'unidade': None, 'nivel': 1}
classificacoes: 2 - Sexo: {'id': 5, 'nome': 'Mulheres', 'unidade': None, 'nivel': 1}
classificacoes: 871 - Faixa etária ideal por curso frequentado: {'id': 47815, 'nome': '6 a 14 anos no ensino fundamental', 'unidade': None, 'nivel': 0}
classificacoes: 871 - Faixa etária ideal por curso frequentado: {'id': 47816, 'nome': '6 a 10 anos nos anos iniciais do ensino fundamental', 'unidade': None, 'nivel': 1}
classificacoes: 871 - Faixa etária ideal por curso frequentado: {'id': 47817, 'nome': '11 a 14 anos nos anos finais do ensino fundamental', 'unidade': None, 'nivel': 1}
classificacoes: 871 - Faixa etária ideal por curso frequentado: {'id': 47818, 'nome': '15 a 17 anos no ensino médio', 'unidade': None, 'nivel': 0}
classificacoes: 871 - Faixa etária ideal por curso frequentado: {'id': 47819, 'nome': '18 a 24 no ensino superior', 'unidade': None, 'nivel': 0}

In [307]:
ano = metadados['periodicidade']['fim']
variavel = metadados['variaveis'][0]['id']

params = {
    "localidades": "N3[all]",
    "classificacao": "2[6794,4,5]|871[47815,47816,47817,47818,47819]"
}

url = f"https://servicodados.ibge.gov.br/api/v3/agregados/{agregado}/periodos/{ano}/variaveis/{variavel}"
resp = requests.get(url, params=params, timeout=20)
resp.raise_for_status()
dados = resp.json()

In [308]:
for linha in dados[0]['resultados']:
  print(linha)

{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '871', 'nome': 'Faixa etária ideal por curso frequentado', 'categoria': {'47815': '6 a 14 anos no ensino fundamental'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '97.0'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '94.9'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '95.9'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '96.2'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '92.9'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '94.9'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '96.4'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '96.1'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '96.3'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '96.8'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '97.0'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '96.8'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '95.1'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '96.8'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '96.3'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '94.1'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '95.7'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '97.4'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '96.7'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '96.0'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '871', 'nome': 'Faixa etária ideal por curso frequentado', 'categoria': {'47816': '6 a 10 anos nos anos iniciais do ensino fundamental'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '95.0'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '95.2'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '92.2'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '95.5'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '93.7'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '87.1'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '91.0'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '93.3'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '94.2'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '93.6'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '94.0'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '94.4'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '94.9'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '94.7'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '95.2'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '91.9'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '94.9'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '93.2'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '93.1'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '93.0'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '90.1'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '92.8'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '93.2'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '93.0'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '94.4'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '93.4'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '871', 'nome': 'Faixa etária ideal por curso frequentado', 'categoria': {'47817': '11 a 14 anos nos anos finais do ensino fundamental'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '92.4'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '85.0'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '86.5'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '81.8'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '84.1'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '82.4'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '91.9'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '89.8'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '88.9'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '91.5'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '83.9'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '89.2'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '89.4'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '89.2'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '87.5'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '86.9'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '93.8'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '89.1'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '87.3'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '93.7'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '90.7'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '90.3'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '89.0'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '87.3'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '91.3'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '92.6'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '88.9'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '871', 'nome': 'Faixa etária ideal por curso frequentado', 'categoria': {'47818': '15 a 17 anos no ensino médio'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '78.8'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '70.7'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '74.5'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '77.4'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '70.5'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '73.3'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '84.3'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '77.5'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '75.1'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '84.2'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '70.5'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '74.7'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '80.5'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '75.3'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '70.0'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '76.2'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '84.8'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '75.6'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '81.0'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '86.5'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '86.6'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '83.6'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '76.7'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '72.2'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '83.8'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '82.2'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '84.6'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '871', 'nome': 'Faixa etária ideal por curso frequentado', 'categoria': {'47819': '18 a 24 no ensino superior'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '24.5'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '23.6'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '24.3'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '27.1'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '22.7'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '28.6'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '32.5'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '20.6'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '29.6'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '23.7'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '26.9'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '22.8'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '25.0'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '19.4'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '28.3'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '21.7'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '26.9'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '28.1'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '32.8'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '33.5'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '36.0'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '32.9'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '29.5'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '30.0'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '27.6'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '31.0'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '48.4'}}]}

In [309]:
print(dados[0]["resultados"][0].keys())
print(dados[0]["resultados"][0]['classificacoes'][0].keys())
print(dados[0]["resultados"][0]['series'][0].keys())

dict_keys(['classificacoes', 'series'])
dict_keys(['id', 'nome', 'categoria'])
dict_keys(['localidade', 'serie'])

In [311]:
linhas = []

for resultado in dados[0]["resultados"]:
    # ------------------------------
    # Sexo
    # ------------------------------
    sexo = resultado["classificacoes"][0]["categoria"]

    # ------------------------------
    # Grupo de idade
    # ------------------------------
    faixa_etaria = resultado["classificacoes"][1]["categoria"]

    # ------------------------------
    # Localidade
    # ------------------------------
    for serie in resultado["series"]:
        estado = serie["localidade"]["nome"]

        # ------------------------------
        # Valor do último ano
        # ------------------------------
        valor = serie["serie"][str(ano)]

        # ------------------------------
        # Montando as linhas
        # ------------------------------
        linhas.append({
            "Estado": estado,
            "Sexo": list(sexo.values())[0],
            "Faixa etária ideal por curso frequentado": list(faixa_etaria.values())[0],
            "Taxa ajustada de frequência escolar (%)": valor
        })
# ==========================================
# 4. DATAFRAME
# ==========================================
df = pd.DataFrame(linhas)

# ==========================================
# 5. CONVERSÃO DO VALOR
# ==========================================
df["Taxa ajustada de frequência escolar (%)"] = pd.to_numeric(
    df["Taxa ajustada de frequência escolar (%)"],
    errors="coerce"
)

# ==========================================
# 6. ORDENAÇÃO
# ==========================================
df = df.sort_values(
    by=["Estado", "Sexo"]
).reset_index(drop=True)

# ==========================================
# 7. VISUALIZAÇÃO
# ==========================================
print("\nQuantidade de linhas:", len(df))
print("\nEstados encontrados:", df["Estado"].nunique())
df

Quantidade de linhas: 405

Estados encontrados: 27

,Estado,Sexo,Faixa etária ideal por curso frequentado,Taxa ajustada de frequência escolar (%)
0,Acre,Homens,6 a 14 anos no ensino fundamental,96.9
1,Acre,Homens,6 a 10 anos nos anos iniciais do ensino fundam...,95.2
2,Acre,Homens,11 a 14 anos nos anos finais do ensino fundame...,80.0
3,Acre,Homens,15 a 17 anos no ensino médio,69.4
4,Acre,Homens,18 a 24 no ensino superior,19.8
...,...,...,...,...
400,Tocantins,Total,6 a 14 anos no ensino fundamental,94.9
401,Tocantins,Total,6 a 10 anos nos anos iniciais do ensino fundam...,91.0
402,Tocantins,Total,11 a 14 anos nos anos finais do ensino fundame...,91.9
403,Tocantins,Total,15 a 17 anos no ensino médio,84.3
404,Tocantins,Total,18 a 24 no ensino superior,32.5

**7142 — frequência líquida ajustada por cor/raça**

In [326]:
agregado = 7142
metadados = verificar_metadados(agregado)
print_metadados(metadados)

id: 7142
nome: Taxa ajustada de frequência escolar líquida, por cor ou raça e faixa etária ideal por curso frequentado
URL: https://sidra.ibge.gov.br/tabela/7142
pesquisa: Pesquisa Nacional por Amostra de Domicílios Contínua anual
assunto: Educação
periodicidade: {'frequencia': 'anual', 'inicio': 2016, 'fim': 2025}
nivelTerritorial: {'Administrativo': ['N1', 'N2', 'N3'], 'Especial': [], 'IBGE': []}
variaveis: [{'id': 10282, 'nome': 'Taxa ajustada de frequência escolar líquida', 'unidade': '%', 'sumarizacao': []}, {'id': 10283, 'nome': 'Coeficiente de variação - Taxa ajustada de frequência escolar líquida', 'unidade': '%', 'sumarizacao': []}]
classificacoes: 86 - Cor ou raça: {'id': 95251, 'nome': 'Total', 'unidade': None, 'nivel': 0}
classificacoes: 86 - Cor ou raça: {'id': 2776, 'nome': 'Branca', 'unidade': None, 'nivel': 1}
classificacoes: 86 - Cor ou raça: {'id': 119525, 'nome': 'Preta ou parda', 'unidade': None, 'nivel': 1}
classificacoes: 871 - Faixa etária ideal por curso frequentado: {'id': 47815, 'nome': '6 a 14 anos no ensino fundamental', 'unidade': None, 'nivel': 0}
classificacoes: 871 - Faixa etária ideal por curso frequentado: {'id': 47816, 'nome': '6 a 10 anos nos anos iniciais do ensino fundamental', 'unidade': None, 'nivel': 1}
classificacoes: 871 - Faixa etária ideal por curso frequentado: {'id': 47817, 'nome': '11 a 14 anos nos anos finais do ensino fundamental', 'unidade': None, 'nivel': 1}
classificacoes: 871 - Faixa etária ideal por curso frequentado: {'id': 47818, 'nome': '15 a 17 anos no ensino médio', 'unidade': None, 'nivel': 0}
classificacoes: 871 - Faixa etária ideal por curso frequentado: {'id': 47819, 'nome': '18 a 24 no ensino superior', 'unidade': None, 'nivel': 0}

In [327]:
ano = metadados['periodicidade']['fim']
variavel = metadados['variaveis'][0]['id']

params = {
    "localidades": "N3[all]",
    "classificacao": "86[95251,2776,119525]|871[47815,47816,47817,47818,47819]"
}

url = f"https://servicodados.ibge.gov.br/api/v3/agregados/{agregado}/periodos/{ano}/variaveis/{variavel}"
resp = requests.get(url, params=params, timeout=20)
resp.raise_for_status()
dados = resp.json()

In [328]:
for linha in dados[0]['resultados']:
  print(linha)

{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '871', 'nome': 'Faixa etária ideal por curso frequentado', 'categoria': {'47815': '6 a 14 anos no ensino fundamental'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '97.0'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '94.9'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '95.9'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '96.2'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '92.9'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '94.9'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '96.4'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '96.1'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '96.3'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '96.8'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '97.0'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '96.8'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '95.1'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '96.8'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '96.3'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '94.1'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '95.7'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '97.4'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '96.7'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '96.0'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '871', 'nome': 'Faixa etária ideal por curso frequentado', 'categoria': {'47816': '6 a 10 anos nos anos iniciais do ensino fundamental'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '95.0'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '95.2'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '92.2'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '95.5'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '93.7'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '87.1'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '91.0'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '93.3'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '94.2'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '93.6'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '94.0'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '94.4'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '94.9'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '94.7'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '95.2'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '91.9'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '94.9'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '93.2'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '93.1'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '93.0'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '90.1'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '92.8'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '93.2'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '93.0'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '94.4'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '93.4'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '871', 'nome': 'Faixa etária ideal por curso frequentado', 'categoria': {'47817': '11 a 14 anos nos anos finais do ensino fundamental'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '92.4'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '85.0'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '86.5'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '81.8'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '84.1'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '82.4'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '91.9'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '89.8'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '88.9'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '91.5'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '83.9'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '89.2'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '89.4'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '89.2'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '87.5'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '86.9'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '93.8'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '89.1'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '87.3'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '93.7'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '90.7'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '90.3'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '89.0'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '87.3'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '91.3'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '92.6'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '88.9'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '871', 'nome': 'Faixa etária ideal por curso frequentado', 'categoria': {'47818': '15 a 17 anos no ensino médio'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '78.8'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '70.7'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '74.5'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '77.4'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '70.5'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '73.3'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '84.3'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '77.5'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '75.1'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '84.2'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '70.5'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '74.7'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '80.5'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '75.3'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '70.0'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '76.2'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '84.8'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '75.6'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '81.0'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '86.5'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '86.6'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '83.6'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '76.7'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '72.2'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '83.8'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '82.2'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '84.6'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '871', 'nome': 'Faixa etária ideal por curso frequentado', 'categoria': {'47819': '18 a 24 no ensino superior'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '24.5'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '23.6'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '24.3'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '27.1'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '22.7'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '28.6'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '32.5'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '20.6'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '29.6'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '23.7'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '26.9'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '22.8'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '25.0'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '19.4'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '28.3'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '21.7'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '26.9'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '28.1'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '32.8'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '33.5'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '36.0'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '32.9'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '29.5'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '30.0'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '27.6'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '31.0'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '48.4'}}]}

In [317]:
linhas = []

for resultado in dados[0]["resultados"]:
    # ------------------------------
    # Cor
    # ------------------------------
    cor = resultado["classificacoes"][0]["categoria"]

    # ------------------------------
    # Grupo de idade
    # ------------------------------
    faixa_etaria = resultado["classificacoes"][1]["categoria"]

    # ------------------------------
    # Localidade
    # ------------------------------
    for serie in resultado["series"]:
        estado = serie["localidade"]["nome"]

        # ------------------------------
        # Valor do último ano
        # ------------------------------
        valor = serie["serie"][str(ano)]

        # ------------------------------
        # Montando as linhas
        # ------------------------------
        linhas.append({
            "Estado": estado,
            "Cor/Raça": list(cor.values())[0],
            "Faixa etária ideal por curso frequentado": list(faixa_etaria.values())[0],
            "Taxa ajustada de frequência escolar (%)": valor
        })
# ==========================================
# 4. DATAFRAME
# ==========================================
df = pd.DataFrame(linhas)

# ==========================================
# 5. CONVERSÃO DO VALOR
# ==========================================
df["Taxa ajustada de frequência escolar (%)"] = pd.to_numeric(
    df["Taxa ajustada de frequência escolar (%)"],
    errors="coerce"
)

# ==========================================
# 6. ORDENAÇÃO
# ==========================================
df = df.sort_values(
    by=["Estado", "Cor/Raça"]
).reset_index(drop=True)

# ==========================================
# 7. VISUALIZAÇÃO
# ==========================================
print("\nQuantidade de linhas:", len(df))
print("\nEstados encontrados:", df["Estado"].nunique())
display(df)

Quantidade de linhas: 405

Estados encontrados: 27

,Estado,Cor/Raça,Faixa etária ideal por curso frequentado,Taxa ajustada de frequência escolar (%)
0,Acre,Branca,6 a 14 anos no ensino fundamental,98.5
1,Acre,Branca,6 a 10 anos nos anos iniciais do ensino fundam...,97.8
2,Acre,Branca,11 a 14 anos nos anos finais do ensino fundame...,85.7
3,Acre,Branca,15 a 17 anos no ensino médio,83.0
4,Acre,Branca,18 a 24 no ensino superior,34.8
...,...,...,...,...
400,Tocantins,Total,6 a 14 anos no ensino fundamental,94.9
401,Tocantins,Total,6 a 10 anos nos anos iniciais do ensino fundam...,91.0
402,Tocantins,Total,11 a 14 anos nos anos finais do ensino fundame...,91.9
403,Tocantins,Total,15 a 17 anos no ensino médio,84.3
404,Tocantins,Total,18 a 24 no ensino superior,32.5

**10422 — conclusão por sexo**

In [360]:
agregado = 10422
metadados = verificar_metadados(agregado)
print_metadados(metadados)

id: 10422
nome: Indicador 4.1.2 - Taxas de conclusão de nível de ensino, por grupos de idade e nivel de ensino e por sexo
URL: https://sidra.ibge.gov.br/tabela/10422
pesquisa: Objetivos de Desenvolvimento Sustentável
assunto: Educação de qualidade
periodicidade: {'frequencia': 'anual', 'inicio': 2016, 'fim': 2025}
nivelTerritorial: {'Administrativo': ['N1', 'N2', 'N3'], 'Especial': [], 'IBGE': []}
variaveis: [{'id': 4721, 'nome': 'Taxa de conclusão de nível de ensino', 'unidade': '%', 'sumarizacao': []}, {'id': 4722, 'nome': 'Coeficiente de variação - Taxa de conclusão de nível de ensino', 'unidade': '%', 'sumarizacao': []}]
classificacoes: 582 - Grupos de idade e nível de ensino: {'id': 59995, 'nome': 'Anos iniciais do ensino fundamental - Pessoas de 13 a 15 anos', 'unidade': None, 'nivel': 0}
classificacoes: 582 - Grupos de idade e nível de ensino: {'id': 59996, 'nome': 'Ensino fundamental - Pessoas de 17 a 19 anos', 'unidade': None, 'nivel': 0}
classificacoes: 582 - Grupos de idade e nível de ensino: {'id': 59997, 'nome': 'Ensino médio - Pessoas de 20 a 22 anos', 'unidade': None, 'nivel': 0}
classificacoes: 2 - Sexo: {'id': 6794, 'nome': 'Total', 'unidade': None, 'nivel': 0}
classificacoes: 2 - Sexo: {'id': 4, 'nome': 'Homens', 'unidade': None, 'nivel': 1}
classificacoes: 2 - Sexo: {'id': 5, 'nome': 'Mulheres', 'unidade': None, 'nivel': 1}

In [361]:
ano = metadados['periodicidade']['fim']
variavel = metadados['variaveis'][0]['id']

params = {
    "localidades": "N3[all]",
    "classificacao": "2[6794,4,5]|582[59995,59996,59997]"
}

url = f"https://servicodados.ibge.gov.br/api/v3/agregados/{agregado}/periodos/{ano}/variaveis/{variavel}"
resp = requests.get(url, params=params, timeout=20)
resp.raise_for_status()
dados = resp.json()

In [362]:
for linha in dados[0]['resultados']:
  print(linha)

{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '582', 'nome': 'Grupos de idade e nível de ensino', 'categoria': {'59995': 'Anos iniciais do ensino fundamental - Pessoas de 13 a 15 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '96.3'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '94.6'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '94.7'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '91.8'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '96.5'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '95.9'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '99.1'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '96.8'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '96.4'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '98.0'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '96.9'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '97.0'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '98.3'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '97.9'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '97.5'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '98.8'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '97.8'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '96.6'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '98.0'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '98.7'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '97.8'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '97.2'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '97.9'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '99.1'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '97.4'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '582', 'nome': 'Grupos de idade e nível de ensino', 'categoria': {'59996': 'Ensino fundamental - Pessoas de 17 a 19 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '90.5'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '87.8'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '91.6'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '93.1'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '88.8'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '90.7'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '94.0'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '92.8'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '92.9'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '95.3'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '87.4'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '90.2'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '93.5'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '92.0'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '88.3'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '88.8'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '94.4'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '93.7'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '94.2'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '96.9'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '94.8'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '93.9'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '90.6'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '96.4'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '94.5'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '96.0'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'6794': 'Total'}}, {'id': '582', 'nome': 'Grupos de idade e nível de ensino', 'categoria': {'59997': 'Ensino médio - Pessoas de 20 a 22 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '70.8'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '65.6'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '79.9'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '79.4'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '69.6'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '73.6'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '81.1'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '75.8'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '74.0'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '81.5'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '69.4'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '66.7'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '76.5'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '70.4'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '73.8'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '72.7'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '78.9'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '71.1'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '81.0'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '87.6'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '78.5'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '77.8'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '74.2'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '70.5'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '74.2'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '82.6'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '84.0'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'4': 'Homens'}}, {'id': '582', 'nome': 'Grupos de idade e nível de ensino', 'categoria': {'59995': 'Anos iniciais do ensino fundamental - Pessoas de 13 a 15 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '95.0'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '90.5'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '94.1'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '90.3'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '95.5'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '95.5'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '99.2'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '95.9'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '95.9'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '97.2'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '95.5'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '97.8'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '97.9'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '98.6'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '97.6'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '96.3'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '98.0'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '95.9'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '98.5'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '97.4'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '97.6'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '99.1'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '95.5'}}]}
{'classificacoes': [{'id': '2', 'nome': 'Sexo', 'categoria': {'4': 'Homens'}}, {'id': '582', 'nome': 'Grupos de idade e nível de ensino', 'categoria': {'59996': 'Ensino fundamental - Pessoas de 17 a 19 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '88.5'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '86.3'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '91.8'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '91.9'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '85.4'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '89.0'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '92.6'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '91.0'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '90.4'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '93.4'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '86.9'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '89.5'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '92.0'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '91.5'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '87.9'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '87.9'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '93.1'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '92.2'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '92.3'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '96.8'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '93.6'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '95.5'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '92.3'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '89.5'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '95.8'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '91.9'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '94.4'}}]}

In [364]:
linhas = []

for resultado in dados[0]["resultados"]:
    # ------------------------------
    # Sexo
    # ------------------------------
    sexo = resultado["classificacoes"][0]["categoria"]

    # ------------------------------
    # Grupo de idade
    # ------------------------------
    grupo_idade = resultado["classificacoes"][1]["categoria"]

    # ------------------------------
    # Localidade
    # ------------------------------
    for serie in resultado["series"]:
        estado = serie["localidade"]["nome"]

        # ------------------------------
        # Valor do último ano
        # ------------------------------
        valor = serie["serie"][str(ano)]

        # ------------------------------
        # Montando as linhas
        # ------------------------------
        linhas.append({
            "Estado": estado,
            "Sexo": list(sexo.values())[0],
            "Grupo de idade": list(grupo_idade.values())[0],
            "Taxas de conclusão de nível de ensino (%)": valor
        })
# ==========================================
# 4. DATAFRAME
# ==========================================
df = pd.DataFrame(linhas)

# ==========================================
# 5. CONVERSÃO DO VALOR
# ==========================================
df["Taxas de conclusão de nível de ensino (%)"] = pd.to_numeric(
    df["Taxas de conclusão de nível de ensino (%)"],
    errors="coerce"
)

# ==========================================
# 6. ORDENAÇÃO
# ==========================================
df = df.sort_values(
    by=["Estado", "Sexo"]
).reset_index(drop=True)

# ==========================================
# 7. VISUALIZAÇÃO
# ==========================================
print("\nQuantidade de linhas:", len(df))
print("\nEstados encontrados:", df["Estado"].nunique())
df

Quantidade de linhas: 243

Estados encontrados: 27

,Estado,Sexo,Grupo de idade,Taxas de conclusão de nível de ensino (%)
0,Acre,Homens,Anos iniciais do ensino fundamental - Pessoas ...,90.5
1,Acre,Homens,Ensino fundamental - Pessoas de 17 a 19 anos,86.3
2,Acre,Homens,Ensino médio - Pessoas de 20 a 22 anos,59.2
3,Acre,Mulheres,Anos iniciais do ensino fundamental - Pessoas ...,98.2
4,Acre,Mulheres,Ensino fundamental - Pessoas de 17 a 19 anos,89.3
...,...,...,...,...
238,Tocantins,Mulheres,Ensino fundamental - Pessoas de 17 a 19 anos,95.6
239,Tocantins,Mulheres,Ensino médio - Pessoas de 20 a 22 anos,87.2
240,Tocantins,Total,Anos iniciais do ensino fundamental - Pessoas ...,99.1
241,Tocantins,Total,Ensino fundamental - Pessoas de 17 a 19 anos,94.0
242,Tocantins,Total,Ensino médio - Pessoas de 20 a 22 anos,81.1

**9910 — conclusão por cor/raça**

In [400]:
agregado = 9910
metadados = verificar_metadados(agregado)
print_metadados(metadados)

id: 9910
nome: Indicador 4.1.2 - Taxas de conclusão de nível de ensino, por grupos de idade e nivel de ensino e por cor ou raça
URL: https://sidra.ibge.gov.br/tabela/9910
pesquisa: Objetivos de Desenvolvimento Sustentável
assunto: Educação de qualidade
periodicidade: {'frequencia': 'anual', 'inicio': 2016, 'fim': 2025}
nivelTerritorial: {'Administrativo': ['N1', 'N2', 'N3'], 'Especial': [], 'IBGE': []}
variaveis: [{'id': 4721, 'nome': 'Taxa de conclusão de nível de ensino', 'unidade': '%', 'sumarizacao': []}, {'id': 4722, 'nome': 'Coeficiente de variação - Taxa de conclusão de nível de ensino', 'unidade': '%', 'sumarizacao': []}]
classificacoes: 582 - Grupos de idade e nível de ensino: {'id': 59995, 'nome': 'Anos iniciais do ensino fundamental - Pessoas de 13 a 15 anos', 'unidade': None, 'nivel': 0}
classificacoes: 582 - Grupos de idade e nível de ensino: {'id': 59996, 'nome': 'Ensino fundamental - Pessoas de 17 a 19 anos', 'unidade': None, 'nivel': 0}
classificacoes: 582 - Grupos de idade e nível de ensino: {'id': 59997, 'nome': 'Ensino médio - Pessoas de 20 a 22 anos', 'unidade': None, 'nivel': 0}
classificacoes: 86 - Cor ou raça: {'id': 95251, 'nome': 'Total', 'unidade': None, 'nivel': 0}
classificacoes: 86 - Cor ou raça: {'id': 2776, 'nome': 'Branca', 'unidade': None, 'nivel': 1}
classificacoes: 86 - Cor ou raça: {'id': 2777, 'nome': 'Preta', 'unidade': None, 'nivel': 1}
classificacoes: 86 - Cor ou raça: {'id': 2779, 'nome': 'Parda', 'unidade': None, 'nivel': 1}

In [401]:
ano = metadados['periodicidade']['fim']
variavel = metadados['variaveis'][0]['id']

params = {
    "localidades": "N3[all]",
    "classificacao": "86[95251,2777,2779]|582[59995,59996,59997]"
}

url = f"https://servicodados.ibge.gov.br/api/v3/agregados/{agregado}/periodos/2025/variaveis/{variavel}"
resp = requests.get(url, params=params, timeout=20)
resp.raise_for_status()
dados = resp.json()

In [389]:
for linha in dados[0]['resultados']:
  print(linha)

{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '582', 'nome': 'Grupos de idade e nível de ensino', 'categoria': {'59995': 'Anos iniciais do ensino fundamental - Pessoas de 13 a 15 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '96.3'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '94.6'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '94.7'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '91.8'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '96.5'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '95.9'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '99.1'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '96.8'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '96.4'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '98.0'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '96.9'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '97.0'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '98.3'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '97.9'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '97.5'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '98.8'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '97.8'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '96.6'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '98.0'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '98.7'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '97.8'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '97.2'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '97.9'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '99.1'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '97.4'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '582', 'nome': 'Grupos de idade e nível de ensino', 'categoria': {'59996': 'Ensino fundamental - Pessoas de 17 a 19 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '90.5'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '87.8'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '91.6'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '93.1'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '88.8'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '90.7'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '94.0'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '92.8'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '92.9'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '95.3'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '87.4'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '90.2'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '93.5'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '92.0'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '88.3'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '88.8'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '94.4'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '93.7'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '94.2'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '96.9'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '94.8'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '93.9'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '90.6'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '96.4'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '94.5'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '96.0'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'95251': 'Total'}}, {'id': '582', 'nome': 'Grupos de idade e nível de ensino', 'categoria': {'59997': 'Ensino médio - Pessoas de 20 a 22 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '70.8'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '65.6'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '79.9'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '79.4'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '69.6'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '73.6'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '81.1'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '75.8'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '74.0'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '81.5'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '69.4'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '66.7'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '76.5'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '70.4'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '73.8'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '72.7'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '78.9'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '71.1'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '81.0'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '87.6'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '78.5'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '77.8'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '74.2'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '70.5'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '74.2'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '82.6'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '84.0'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'2777': 'Preta'}}, {'id': '582', 'nome': 'Grupos de idade e nível de ensino', 'categoria': {'59995': 'Anos iniciais do ensino fundamental - Pessoas de 13 a 15 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '100.0'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '94.8'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '90.8'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '82.3'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '96.7'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '100.0'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '100.0'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '96.2'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '95.0'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '100.0'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '98.3'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '87.0'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '97.0'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '97.4'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '98.5'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '98.1'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '99.3'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '94.7'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '97.7'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '99.6'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '79.7'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '100.0'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '91.5'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '95.1'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '96.8'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '100.0'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '93.1'}}]}
{'classificacoes': [{'id': '86', 'nome': 'Cor ou raça', 'categoria': {'2777': 'Preta'}}, {'id': '582', 'nome': 'Grupos de idade e nível de ensino', 'categoria': {'59996': 'Ensino fundamental - Pessoas de 17 a 19 anos'}}], 'series': [{'localidade': {'id': '11', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rondônia'}, 'serie': {'2025': '100.0'}}, {'localidade': {'id': '12', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Acre'}, 'serie': {'2025': '84.4'}}, {'localidade': {'id': '13', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amazonas'}, 'serie': {'2025': '91.9'}}, {'localidade': {'id': '14', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Roraima'}, 'serie': {'2025': '80.1'}}, {'localidade': {'id': '15', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pará'}, 'serie': {'2025': '87.3'}}, {'localidade': {'id': '16', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Amapá'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '17', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Tocantins'}, 'serie': {'2025': '92.1'}}, {'localidade': {'id': '21', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Maranhão'}, 'serie': {'2025': '94.1'}}, {'localidade': {'id': '22', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Piauí'}, 'serie': {'2025': '96.0'}}, {'localidade': {'id': '23', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Ceará'}, 'serie': {'2025': '97.9'}}, {'localidade': {'id': '24', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Norte'}, 'serie': {'2025': '100.0'}}, {'localidade': {'id': '25', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraíba'}, 'serie': {'2025': '87.4'}}, {'localidade': {'id': '26', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Pernambuco'}, 'serie': {'2025': '87.7'}}, {'localidade': {'id': '27', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Alagoas'}, 'serie': {'2025': '87.9'}}, {'localidade': {'id': '28', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Sergipe'}, 'serie': {'2025': '87.8'}}, {'localidade': {'id': '29', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Bahia'}, 'serie': {'2025': '87.8'}}, {'localidade': {'id': '31', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Minas Gerais'}, 'serie': {'2025': '90.1'}}, {'localidade': {'id': '32', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Espírito Santo'}, 'serie': {'2025': '95.3'}}, {'localidade': {'id': '33', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio de Janeiro'}, 'serie': {'2025': '90.8'}}, {'localidade': {'id': '35', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'São Paulo'}, 'serie': {'2025': '97.3'}}, {'localidade': {'id': '41', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Paraná'}, 'serie': {'2025': '92.5'}}, {'localidade': {'id': '42', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Santa Catarina'}, 'serie': {'2025': '97.1'}}, {'localidade': {'id': '43', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Rio Grande do Sul'}, 'serie': {'2025': '84.9'}}, {'localidade': {'id': '50', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso do Sul'}, 'serie': {'2025': '83.0'}}, {'localidade': {'id': '51', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Mato Grosso'}, 'serie': {'2025': '97.9'}}, {'localidade': {'id': '52', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Goiás'}, 'serie': {'2025': '92.9'}}, {'localidade': {'id': '53', 'nivel': {'id': 'N3', 'nome': 'Unidade da Federação'}, 'nome': 'Distrito Federal'}, 'serie': {'2025': '95.9'}}]}

In [402]:
linhas = []

for resultado in dados[0]["resultados"]:
    # ------------------------------
    # Cor
    # ------------------------------
    cor = resultado["classificacoes"][0]["categoria"]

    # ------------------------------
    # Grupo de idade
    # ------------------------------
    grupo_idade = resultado["classificacoes"][1]["categoria"]

    # ------------------------------
    # Localidade
    # ------------------------------
    for serie in resultado["series"]:
        estado = serie["localidade"]["nome"]

        # ------------------------------
        # Valor do último ano
        # ------------------------------
        valor = serie["serie"][str(ano)]

        # ------------------------------
        # Montando as linhas
        # ------------------------------
        linhas.append({
            "Estado": estado,
            "Cor/raça": list(cor.values())[0],
            "Grupo de idade": list(grupo_idade.values())[0],
            "Taxas de conclusão de nível de ensino (%)": valor
        })
# ==========================================
# 4. DATAFRAME
# ==========================================
df = pd.DataFrame(linhas)

# ==========================================
# 5. CONVERSÃO DO VALOR
# ==========================================
df["Taxas de conclusão de nível de ensino (%)"] = pd.to_numeric(
    df["Taxas de conclusão de nível de ensino (%)"],
    errors="coerce"
)

# ==========================================
# 6. ORDENAÇÃO
# ==========================================
df = df.sort_values(
    by=["Estado", "Cor/raça"]
).reset_index(drop=True)

# ==========================================
# 7. VISUALIZAÇÃO
# ==========================================
print("\nQuantidade de linhas:", len(df))
print("\nEstados encontrados:", df["Estado"].nunique())
df

Quantidade de linhas: 243

Estados encontrados: 27

,Estado,Cor/raça,Grupo de idade,Taxas de conclusão de nível de ensino (%)
0,Acre,Parda,Anos iniciais do ensino fundamental - Pessoas ...,94.4
1,Acre,Parda,Ensino fundamental - Pessoas de 17 a 19 anos,88.0
2,Acre,Parda,Ensino médio - Pessoas de 20 a 22 anos,64.0
3,Acre,Preta,Anos iniciais do ensino fundamental - Pessoas ...,94.8
4,Acre,Preta,Ensino fundamental - Pessoas de 17 a 19 anos,84.4
...,...,...,...,...
238,Tocantins,Preta,Ensino fundamental - Pessoas de 17 a 19 anos,92.1
239,Tocantins,Preta,Ensino médio - Pessoas de 20 a 22 anos,71.1
240,Tocantins,Total,Anos iniciais do ensino fundamental - Pessoas ...,99.1
241,Tocantins,Total,Ensino fundamental - Pessoas de 17 a 19 anos,94.0
242,Tocantins,Total,Ensino médio - Pessoas de 20 a 22 anos,81.1